### PR TITLE
feat: add Typescript extension

### PR DESCRIPTION
**Pull request by Krisztiaan**
## Summary

Extending `@types/react-native` with `react-native-tvos` specific additions using the already existing flow typings and some research to narrow it down where possible.

## Changelog

[Typescript] [FEAT] - Added Typescript typings

## Test Plan

- try importing `TVEventHandler` in a typescript project

Closes: #41

### CODE REVIEW

**Review by dlowder-salesforce — APPROVED** [review]

**Comment by olafurnsig** [comment]
I'm a bit confused here, won't @types/react-native always be overruled by the npm package?

Or would we be importing from 'react-native-tvos' instead?

**Comment by Krisztiaan** [comment]
`@types/react-native` is the original react-native typings, and that is extended by this `.d.ts`. On the top, we're importing it from the `@types` package, so we're not "re-declaring" the whole package, but extending it. You can try it by copying it in your own project with `react-native-tvos` and observing that it "just works"

**Comment by dlowder-salesforce** [comment]
I made a quick test project using https://github.com/react-native-community/react-native-template-typescript ... switched it to use this branch, and it seems to "just work".  (Although the template doesn't seem to come with very strict typechecking, but I'm not really an expert in this area :) )  So I'm cool to merge this, and hopefully the community will let me and you know if there are any problems.

**Comment by adbl** [comment]
@Krisztiaan hmm I'm not getting this to work, it seems I do get the additional types correctly, but everything standard from react-native is not. e.g.:

```
$ yarn run tsc

src/modules/Empty.tsx:2:9 - error TS2305: Module '"react-native"' has no exported member 'View'.

2 import {View} from 'react-native';
```

for `Empty.tsx`
```
import React from 'react';
import {View} from 'react-native';

const Empty: React.FC = () => <View />;
export default Empty;
```

Running typescript 4.0.2. It's possible I have something in `tsconfig.json` causing trouble... any ideas?

**Comment by adbl** [comment]
Oh, when running with `skipLibCheck: false` I'm seeing some things which seem related:

```

node_modules/react-native/index.d.ts:4:3 - error TS2667: Imports are not permitted in module augmentations. Consider moving them to the enclosing external module.

4   import React from 'react';
    ~~~~~~

node_modules/react-native/index.d.ts:4:21 - error TS2307: Cannot find module 'react' or its corresponding type declarations.

4   import React from 'react';
                      ~~~~~~~

node_modules/react-native/index.d.ts:6:3 - error TS2667: Imports are not permitted in module augmentations. Consider moving them to the enclosing external module.

6   import { ViewProps, ScrollViewProps } from '@types/react-native';
    ~~~~~~

node_modules/react-native/index.d.ts:6:46 - error TS6137: Cannot import type declaration files. Consider importing 'react-native' instead of '@types/react-native'.

6   import { ViewProps, ScrollViewProps } from '@types/react-native';
                                               ~~~~~~~~~~~~~~~~~~~~~
```

Also tried with typescript 3.8.3 same problem.

**Comment by adbl** [comment]
Here is a related SO question: https://stackoverflow.com/questions/40456231/typescript-module-augmentation-overwrites-the-original-module

Per the answer, the fix is to change `react-native-tvos/index.d.ts` to:
```
import React from 'react';
import {ViewProps, ScrollViewProps} from 'react-native';

declare module 'react-native' {
...
}
```

But it doesn't see the regular `react-native` type definitions, because `import 'react-native'` is imports itself? I think a solution is to add the types to `@types/react-native-tvos` which augments `@types/react-native`, then include in the README here a reference to it for whoever is using typescript. I guess we'll also have to change our code to say `import ... from `react-native-tvos` in all places which uses TV specific features, annoying.

**Comment by adbl** [comment]
Actually, couldn't we just add the types to `@types/react-native`? There are already things like `TVParallaxProperties` in there.

I can make a PR for that unless anyone disagree? @dlowder-salesforce do you have an opinion?

**Comment by dlowder-salesforce** [comment]
@adbl I agree, that would be simplest.  @Krisztiaan would you be ok with that?

**Comment by adbl** [comment]
Hoping you are ok with it @Krisztiaan! Once the PR gets merged, I'll open another one to remove `index.d.ts` from here.

**Comment by Krisztiaan** [comment]
@dlowder-salesforce Sure thing, I've commented on that PR as well. It's also something I wanted to do but didn't bother.

These errors are easily fixable though in this repository as well. I'm personally not a huge fan of the `DefinitelyTyped` mo.

**Comment by Krisztiaan** [comment]
It should be a simple option to extend the `DefinitelyTyped` definition.
Maybe solutions off the top of my head:
- use `/// <reference types="react-native" />`
- replace `@types/react-native` with `react-native` (TSC _should_ be smart about this, see [Module Augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation))

I'm currently working on a SwiftUI project, so if you could try some of the alternatives, that'd be really nice.

I personally would prefer if there'd be an `index.d.ts` in every repository where it's possible (this being one of them), instead of the whole `DefinitelyTyped`. Maybe one day even `react-native` will be `TypeScript`..

**Comment by adbl** [comment]
> @adbl It should be a simple option to extend the `DefinitelyTyped` definition.
> Maybe solutions off the top of my head:
> 
> * use `/// <reference types="react-native" />`

I'll check this out and see if it has any effect, because:

> * replace `@types/react-native` with `react-native` (TSC _should_ be smart about this, see [Module Augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation))

this isn't working at the moment, it seems `react-native` resolves to itself due to the package name.

> 
> I'm currently working on a SwiftUI project, so if you could try these options, that'd be really nice.
> 
> I personally would prefer if there'd be an `index.d.ts` in every repository where it's possible (this being one of them), instead of the whole `DefinitelyTyped`. Maybe one day even `react-native` will be `TypeScript`..

**Comment by adbl** [comment]
I tried the following with the same result:

```
/// <reference types="react-native" />

import React from 'react';
import { ViewProps, ScrollViewProps } from '@types/react-native';

declare module 'react-native' {
...
```

I will proceed to try and get it in @types/react-native

**Comment by Krisztiaan** [comment]
I've also encountered @adbl please see #119
As per my local testing, it should work. Circumvents the way typescript recognizes typings.

**Comment by adbl** [comment]
Great, it does indeed work!

**Comment by EyMaddis** [comment]
Very late to the party, but in my project, import `ViewProps` directly no longer works now.

I have problems like 
```
 type MyComProps = ViewProps
 function MyCom(props: MyComProps) {
  return <View {...props} />
}

<MyComp style={...} /> ---> `style does not exist in ....`
```

Following the type definition via Vscode will go to the `ReactNativeTVTypes.d.ts` and only properties like nextFocusDown are available now...

**Comment by Krisztiaan** [comment]
@EyMaddis without looking too deep into it, you may find `https://www.npmjs.com/package/deprecated-react-native-prop-types/` to work to restore the types. Otherwise, the now built in types should be used, and this package updated.

**Comment by EyMaddis** [comment]
Thanks, but this seems to be a general problem. The file also breaks prop types for Touchables for me. I worked around it using `patch-package` to the type to TVViewProps in ReactNativeTVTypes.d.ts.
Might be my setup as I am also overwriting types via react-native-web but I do not really see a reason why that should happen. 
Instead of declaration merging, this just fully overrides the type and Vscode. Very odd.

**Comment by Krisztiaan** [comment]
Unfortunately, it's been a few years since I've worked on a `tvos` project, but when I do pick it up again, this'll be something to look at, unless you want to give it a go, figure out what's up (I'm way out of the loop at the moment), and create a PR, I'd be very happy to review.

**Pull request merged**
