### PR TITLE
update RN docs links to reactnative.dev

### PR DESCRIPTION
**Pull request by bell-steven**
## Summary

Updated React Native docs links to reactnative.dev

## Changelog

[INTERNAL] [CHANGED] - update RN docs links to reactnative.dev

## Test Plan

Tested new links and made sure they work

### CODE REVIEW

**Comment by dlowder-salesforce** [comment]
Has this been merged to the main repo yet?

**Comment by Naturalclar** [comment]
@dlowder-salesforce The url change has been made in the main repo 👍 
https://github.com/facebook/react-native/commit/c0d8c1db9077d08c3832b23e959bf70ad204307d

**Comment by bell-steven** [comment]
@lucianomlima I updated the docs links to https.  There are a whole bunch of other links that could probably be updated to https, but I would have thought it should be a separate PR.

**Comment by dlowder-salesforce** [comment]
Since this is a fork of the main repo, it would probably be better to merge the existing  commit from the main repo.... otherwise there may be merge conflicts and problems down the road...

**Comment by lucianomlima** [comment]
Good job @bell-steven

**Pull request closed without merging**
