### PR TITLE
fix: hacky type extension import

### PR DESCRIPTION
**Pull request by Krisztiaan**
## Summary

Continuation and fix of #102 

## Changelog

[General] [Fixed] - Working typescript extension

## Test Plan

Run `yarn tsc` after following guide in `README.md`

### CODE REVIEW

**Comment by adbl** [comment]
Awesome! 

`tsc` accepts the augmentation this way, but RN bundler didn't like `import 'react-native/tvos-types'`, `import 'react-native/tvos-types.d'` worked.

Including `"skipLibCheck": true` still gives errors because of import inside module augmentation, at least in typescript 4. I have fixed this in https://github.com/adbl/react-native-tvos/tree/fix-typescript-module-augmentation based on your branch, will you include it here?

**Comment by Krisztiaan** [comment]
Thanks @adbl I've merged your fix to this PR!

**Review by dlowder-salesforce — APPROVED** [review]
LGTM, let me know when you think it's ready to be merged.

**Comment by Krisztiaan** [comment]
@dlowder-salesforce We both tested these changes, should be safe and OK to go. Going forward, it'd be nice to update thes types with any new development

**Comment by adbl** [comment]
Yes! I would just change the README to say `import 'react-native/tvos-types.d'` since bundler didn't agree without `.d`

**Comment by Krisztiaan** [comment]
Weird, TS 4.0.3 did not complain.

**Comment by adbl** [comment]
I didn't get any errors from typescript, but the react native bundler so some of the babel stuff I guess.

**Comment by Krisztiaan** [comment]
LGTM

**Comment by chika-kasymov** [comment]
When installing RN for tvOS like this `"react-native": "npm:react-native-tvos@latest"`, there is no the `tvos-types.d` file in the `node_modules/react-native`.  Maybe we need to include the `tvos-types.d` in the `package.json`'s `files` section?

**Pull request merged**
