### PR TITLE
Feature: Add View containing the UIFocusGuide

### PR DESCRIPTION
**Pull request by hufkens**
## Summary

This is a first step in adding a FocusGuide Component. Please note that I need some help with the `FocusGuideView.js` code in the AppleTV folder. In our project it was a simple JS file and I don't have that much experience how to add it properly to the React Native core. 

I'm open to learning, please help!  

## Changelog

* Added support for UIFocusGuide that wil help direct the focus from one View to another View.

## Test Plan

I can add a demo project somewhere if the code has been properly approved. It should work like this in the end:

```
import React, { Component } from 'react';
import { 
  TVEventHandler, 
  findNodeHandle, 
  View, 
  TouchableOpacity, 
  Text,
  FocusGuideView
} from 'react-native';

const padding = 100;
const width = 100;
const height = 60;

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = { destination: undefined };
  }

  componentDidMount() {
    const eventHandler = new TVEventHandler();

    eventHandler.enable(this, (cmp, event) => {
      const { eventType } = event;
      if (eventType === 'focus') {
        const { tag } = event;
        if (tag === this.buttonTopRightTag) {
          this.setState({ destination: this.buttonBottomLeftTag });
        }
        if (tag === this.buttonBottomLeftTag) {
          this.setState({ destination: this.buttonTopRightTag });
        }
      }
    })    
  }

  render() {
    const { destination } = this.state;
    return (
      <View style={{ flex: 1 }}>
        <TouchableOpacity
          style={{ position: 'absolute', top: padding, left: padding, width, height }}
        >
          <Text>"Left Top"</Text>
        </TouchableOpacity>
        <TouchableOpacity
          ref={component =>
            (this.buttonTopRightTag = findNodeHandle(component))
          }
          style={{ position: 'absolute', top: padding, left: padding * 5, width, height }}
          >
          <Text>"Right Top"</Text>
        </TouchableOpacity>
        <TouchableOpacity
          ref={component =>
            (this.buttonBottomLeftTag = findNodeHandle(component))
          }
          style={{ position: 'absolute', top: padding * 3, left: padding, width, height }}
          >
          <Text>"Left Bottom"</Text>
        </TouchableOpacity>
        <FocusGuideView
          style={{
            position: 'absolute',
            width, 
            height,
            top: padding * 3,
            left: padding * 5,
            backgroundColor: 'pink',
            opacity: 0.3,
          }}
          destinationTags={[destination]}
        />
      </View>
    );
  }
}
```

### CODE REVIEW

**Comment by hufkens** [comment]
@douglowder I need some help with the JS code and adding it properly to the framework. Looking forward to your feedback.

**Comment by dlowder-salesforce** [comment]
@hufkens I'm going to have a look at this to see if it can be merged to the release I'm currently actively working on (0.58.6).  I'll create a feature branch and add this, and make the appropriate changes to `FocusGuideView.js`, and add your example to the `RNTester` examples, and see how it goes :)

**Comment by hufkens** [comment]
@douglowder Thanks. I had a JS version of the Component, but haven't figured it out how to convert it to typed. So any help there is appreciated.

**Comment by dlowder-salesforce** [comment]
Ok I got everything working in https://github.com/react-native-community/react-native-tvos/commit/5cdc3bbd962f61bd049399931fb5e700d524387e

**Comment by hufkens** [comment]
@douglowder Thanks.

**Comment by hufkens** [comment]
Since the code is already in the 0.58.6 branch, should we close this PR?
What about version 0.59.8 We are running on 0.59.8 now.

**Comment by dlowder-salesforce** [comment]
I haven't done any work yet on fully testing the 0.59.8 branch.  Let me have a look and see what's needed, then we can close this and do a PR against that branch.

**Comment by dlowder-salesforce** [comment]
@hufkens I now have a 0.59.8 branch with the focus guide feature. See https://github.com/react-native-community/react-native-tvos/commits/tvos-v0.59.8-focusguide

I figured out how to implement the JS side of the focus guide, so that application code doesn't have to reference view tags.  Example app code:

```js
class TVFocusGuideExample extends React.Component<
  $FlowFixMeProps,
  {
    destination: ?Object,
    destinationText: string,
  },
> {
  constructor(props: Object) {
    super(props);
    this.state = {
      destination: undefined,
      destinationText: 'null',
    };
  }

  buttonTopRight: ?Object;

  buttonBottomLeft: ?Object;

  _setDestination(destination: ?Object, destinationText: string) {
    this.setState({
      destination,
      destinationText,
    });
  }

  render() {
    if (!Platform.isTVOS) {
      return (
        <View>
          <Text>This example is intended to be run on Apple TV.</Text>
        </View>
      );
    }
    const destinations = this.state.destination ? [this.state.destination] : [];
    return (
      <View style={styles.container}>
        <View style={styles.rowContainer}>
          <TouchableOpacity
            onPress={() => {}}
            style={{
              width,
              height,
            }}>
            <Text style={styles.buttonText}>Left Top</Text>
          </TouchableOpacity>
          <TouchableOpacity
            onPress={() => {}}
            onFocus={() =>
              this._setDestination(this.buttonBottomLeft, 'bottom left')
            }
            ref={component => (this.buttonTopRight = component)}
            style={{
              width,
              height,
            }}>
            <Text style={styles.buttonText}>Right Top</Text>
          </TouchableOpacity>
          <View
            style={{
              width,
              height,
            }}>
            <Text style={styles.buttonText}>
              Focus guide points to {this.state.destinationText}
            </Text>
          </View>
        </View>
        <View style={styles.rowContainer}>
          <TouchableOpacity
            onPress={() => {}}
            onFocus={() =>
              this._setDestination(this.buttonTopRight, 'top right')
            }
            ref={component => (this.buttonBottomLeft = component)}
            style={{
              width,
              height,
            }}>
            <Text style={styles.buttonText}>Left Bottom</Text>
          </TouchableOpacity>
          <View style={styles.focusGuide}>
            <Text style={styles.buttonText}>Focus guide</Text>
            <TVFocusGuideView destinations={destinations} />
          </View>
        </View>
      </View>
    );
  }
}
```

**Comment by dlowder-salesforce** [comment]
@hufkens I'm going to go ahead and merge this, and then do another PR for the changes we've been discussing :)

**Pull request merged**
